[2024-04-04 20:41:40,668] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: meu_primeiro_dag.cria_pasta scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04 20:41:40,672] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: meu_primeiro_dag.cria_pasta scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04 20:41:40,672] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-04 20:41:40,672] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-04 20:41:40,672] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-04 20:41:40,688] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-04-03 00:00:00+00:00
[2024-04-04 20:41:40,689] {standard_task_runner.py:52} INFO - Started process 573259 to run task
[2024-04-04 20:41:40,691] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'meu_primeiro_dag', 'cria_pasta', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/meu_primeiro_dag.py', '--cfg-path', '/tmp/tmp4otrlak1', '--error-file', '/tmp/tmpns69nue0']
[2024-04-04 20:41:40,691] {standard_task_runner.py:80} INFO - Job 9: Subtask cria_pasta
[2024-04-04 20:41:40,727] {task_command.py:370} INFO - Running <TaskInstance: meu_primeiro_dag.cria_pasta scheduled__2024-04-03T00:00:00+00:00 [running]> on host TEC017860.
[2024-04-04 20:41:40,771] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=meu_primeiro_dag
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-04-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-03T00:00:00+00:00
[2024-04-04 20:41:40,772] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-04-04 20:41:40,772] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/pasta"']
[2024-04-04 20:41:40,775] {subprocess.py:85} INFO - Output:
[2024-04-04 20:41:40,776] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2024-04-04 20:41:40,776] {subprocess.py:96} INFO - Command exited with return code 1
[2024-04-04 20:41:40,782] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-04 20:41:40,783] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=meu_primeiro_dag, task_id=cria_pasta, execution_date=20240403T000000, start_date=20240404T234140, end_date=20240404T234140
[2024-04-04 20:41:40,800] {standard_task_runner.py:92} ERROR - Failed to execute job 9 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 573259)
[2024-04-04 20:41:40,828] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-04 20:41:40,838] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-04 20:46:59,525] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: meu_primeiro_dag.cria_pasta scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04 20:46:59,530] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: meu_primeiro_dag.cria_pasta scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04 20:46:59,530] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-04 20:46:59,530] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-04 20:46:59,530] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-04 20:46:59,545] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-04-03 00:00:00+00:00
[2024-04-04 20:46:59,546] {standard_task_runner.py:52} INFO - Started process 574523 to run task
[2024-04-04 20:46:59,548] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'meu_primeiro_dag', 'cria_pasta', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/meu_primeiro_dag.py', '--cfg-path', '/tmp/tmpl3albnx8', '--error-file', '/tmp/tmpl114rcwv']
[2024-04-04 20:46:59,549] {standard_task_runner.py:80} INFO - Job 9: Subtask cria_pasta
[2024-04-04 20:46:59,581] {task_command.py:370} INFO - Running <TaskInstance: meu_primeiro_dag.cria_pasta scheduled__2024-04-03T00:00:00+00:00 [running]> on host TEC017860.
[2024-04-04 20:46:59,623] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=meu_primeiro_dag
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-04-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-03T00:00:00+00:00
[2024-04-04 20:46:59,624] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-04-04 20:46:59,624] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/dimitri/dimitri/airflowalura/pasta"']
[2024-04-04 20:46:59,627] {subprocess.py:85} INFO - Output:
[2024-04-04 20:46:59,629] {subprocess.py:96} INFO - Command exited with return code 0
[2024-04-04 20:46:59,648] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=meu_primeiro_dag, task_id=cria_pasta, execution_date=20240403T000000, start_date=20240404T234659, end_date=20240404T234659
[2024-04-04 20:46:59,691] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-04 20:46:59,702] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
