[2024-04-05 19:22:50,585] {processor.py:153} INFO - Started process (PID=721384) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:22:50,585] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:22:50,586] {logging_mixin.py:115} INFO - [2024-04-05 19:22:50,586] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:22:50,589] {logging_mixin.py:115} INFO - [2024-04-05 19:22:50,588] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 1, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2024-04-05 19:22:50,589] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:22:50,616] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.034 seconds
[2024-04-05 19:23:24,697] {processor.py:153} INFO - Started process (PID=721524) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:23:24,699] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:23:24,700] {logging_mixin.py:115} INFO - [2024-04-05 19:23:24,700] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:23:24,705] {logging_mixin.py:115} INFO - [2024-04-05 19:23:24,705] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:23:24,705] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:23:24,725] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.030 seconds
[2024-04-05 19:23:57,483] {processor.py:153} INFO - Started process (PID=721661) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:23:57,486] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:23:57,486] {logging_mixin.py:115} INFO - [2024-04-05 19:23:57,486] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:23:57,491] {logging_mixin.py:115} INFO - [2024-04-05 19:23:57,490] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:23:57,491] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:23:57,510] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.031 seconds
[2024-04-05 19:24:25,413] {processor.py:153} INFO - Started process (PID=721771) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:24:25,413] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:24:25,414] {logging_mixin.py:115} INFO - [2024-04-05 19:24:25,414] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:24:25,418] {logging_mixin.py:115} INFO - [2024-04-05 19:24:25,418] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:24:25,418] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:24:25,437] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.026 seconds
[2024-04-05 19:24:59,597] {processor.py:153} INFO - Started process (PID=721922) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:24:59,600] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:24:59,600] {logging_mixin.py:115} INFO - [2024-04-05 19:24:59,600] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:24:59,604] {logging_mixin.py:115} INFO - [2024-04-05 19:24:59,604] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:24:59,605] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:24:59,626] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.031 seconds
[2024-04-05 19:25:35,670] {processor.py:153} INFO - Started process (PID=722064) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:25:35,671] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:25:35,671] {logging_mixin.py:115} INFO - [2024-04-05 19:25:35,671] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:25:35,677] {logging_mixin.py:115} INFO - [2024-04-05 19:25:35,676] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:25:35,677] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:25:35,697] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.030 seconds
[2024-04-05 19:26:08,307] {processor.py:153} INFO - Started process (PID=722196) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:26:08,309] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:26:08,309] {logging_mixin.py:115} INFO - [2024-04-05 19:26:08,309] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:26:08,314] {logging_mixin.py:115} INFO - [2024-04-05 19:26:08,313] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:26:08,314] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:26:08,333] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.028 seconds
[2024-04-05 19:26:42,569] {processor.py:153} INFO - Started process (PID=722332) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:26:42,572] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:26:42,573] {logging_mixin.py:115} INFO - [2024-04-05 19:26:42,572] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:26:42,579] {logging_mixin.py:115} INFO - [2024-04-05 19:26:42,578] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:26:42,579] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:26:42,598] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.033 seconds
[2024-04-05 19:27:15,149] {processor.py:153} INFO - Started process (PID=722461) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:27:15,152] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:27:15,152] {logging_mixin.py:115} INFO - [2024-04-05 19:27:15,152] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:27:15,157] {logging_mixin.py:115} INFO - [2024-04-05 19:27:15,156] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:27:15,157] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:27:15,180] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.033 seconds
[2024-04-05 19:27:47,248] {processor.py:153} INFO - Started process (PID=722583) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:27:47,250] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:27:47,251] {logging_mixin.py:115} INFO - [2024-04-05 19:27:47,251] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:27:47,256] {logging_mixin.py:115} INFO - [2024-04-05 19:27:47,255] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:27:47,256] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:27:47,278] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.033 seconds
[2024-04-05 19:28:20,916] {processor.py:153} INFO - Started process (PID=722713) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:28:20,918] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:28:20,918] {logging_mixin.py:115} INFO - [2024-04-05 19:28:20,918] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:28:20,923] {logging_mixin.py:115} INFO - [2024-04-05 19:28:20,923] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:28:20,923] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:28:20,943] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.031 seconds
[2024-04-05 19:28:53,290] {processor.py:153} INFO - Started process (PID=722842) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:28:53,292] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:28:53,292] {logging_mixin.py:115} INFO - [2024-04-05 19:28:53,292] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:28:53,297] {logging_mixin.py:115} INFO - [2024-04-05 19:28:53,297] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:28:53,297] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:28:53,320] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.034 seconds
[2024-04-05 19:29:28,068] {processor.py:153} INFO - Started process (PID=722974) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:29:28,071] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:29:28,072] {logging_mixin.py:115} INFO - [2024-04-05 19:29:28,072] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:29:28,076] {logging_mixin.py:115} INFO - [2024-04-05 19:29:28,076] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:29:28,077] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:29:28,101] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.036 seconds
[2024-04-05 19:29:59,921] {processor.py:153} INFO - Started process (PID=723102) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:29:59,923] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:29:59,924] {logging_mixin.py:115} INFO - [2024-04-05 19:29:59,924] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:29:59,928] {logging_mixin.py:115} INFO - [2024-04-05 19:29:59,928] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:29:59,929] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:29:59,951] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.032 seconds
[2024-04-05 19:30:35,893] {processor.py:153} INFO - Started process (PID=723240) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:30:35,896] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:30:35,896] {logging_mixin.py:115} INFO - [2024-04-05 19:30:35,896] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:30:35,904] {logging_mixin.py:115} INFO - [2024-04-05 19:30:35,904] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:30:35,904] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:30:35,924] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.033 seconds
[2024-04-05 19:31:07,251] {processor.py:153} INFO - Started process (PID=723362) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:31:07,254] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:31:07,254] {logging_mixin.py:115} INFO - [2024-04-05 19:31:07,254] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:31:07,259] {logging_mixin.py:115} INFO - [2024-04-05 19:31:07,259] {dagbag.py:320} ERROR - Failed to import: /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-05 19:31:07,259] {processor.py:653} WARNING - No viable dags retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:31:07,279] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.031 seconds
[2024-04-05 19:31:47,948] {processor.py:153} INFO - Started process (PID=723556) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:31:47,950] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:31:47,951] {logging_mixin.py:115} INFO - [2024-04-05 19:31:47,951] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:31:48,110] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:31:48,224] {logging_mixin.py:115} INFO - [2024-04-05 19:31:48,224] {manager.py:508} INFO - Created Permission View: can delete on DAG:dados_climaticos
[2024-04-05 19:31:48,241] {logging_mixin.py:115} INFO - [2024-04-05 19:31:48,240] {manager.py:508} INFO - Created Permission View: can read on DAG:dados_climaticos
[2024-04-05 19:31:48,254] {logging_mixin.py:115} INFO - [2024-04-05 19:31:48,254] {manager.py:508} INFO - Created Permission View: can edit on DAG:dados_climaticos
[2024-04-05 19:31:48,254] {logging_mixin.py:115} INFO - [2024-04-05 19:31:48,254] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:31:48,259] {logging_mixin.py:115} INFO - [2024-04-05 19:31:48,259] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2024-04-05 19:31:48,265] {logging_mixin.py:115} INFO - [2024-04-05 19:31:48,265] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-04-05 19:31:48,288] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.343 seconds
[2024-04-05 19:32:34,037] {processor.py:153} INFO - Started process (PID=723974) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:32:34,037] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:32:34,038] {logging_mixin.py:115} INFO - [2024-04-05 19:32:34,038] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:32:34,200] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:32:34,213] {logging_mixin.py:115} INFO - [2024-04-05 19:32:34,213] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:32:34,335] {logging_mixin.py:115} INFO - [2024-04-05 19:32:34,335] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-04-05 19:32:34,360] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.326 seconds
[2024-04-05 19:33:30,318] {processor.py:153} INFO - Started process (PID=724487) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:33:30,319] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:33:30,320] {logging_mixin.py:115} INFO - [2024-04-05 19:33:30,320] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:33:30,439] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:33:30,451] {logging_mixin.py:115} INFO - [2024-04-05 19:33:30,451] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:33:30,537] {logging_mixin.py:115} INFO - [2024-04-05 19:33:30,537] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-05-08T00:00:00+00:00, run_after=2023-05-15T00:00:00+00:00
[2024-04-05 19:33:30,553] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.236 seconds
[2024-04-05 19:34:15,303] {processor.py:153} INFO - Started process (PID=724839) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:34:15,307] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:34:15,307] {logging_mixin.py:115} INFO - [2024-04-05 19:34:15,307] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:34:15,403] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:34:15,412] {logging_mixin.py:115} INFO - [2024-04-05 19:34:15,412] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:34:15,488] {logging_mixin.py:115} INFO - [2024-04-05 19:34:15,487] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-31T00:00:00+00:00, run_after=2023-08-07T00:00:00+00:00
[2024-04-05 19:34:15,504] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.205 seconds
[2024-04-05 19:35:17,092] {processor.py:153} INFO - Started process (PID=725190) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:35:17,093] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:35:17,093] {logging_mixin.py:115} INFO - [2024-04-05 19:35:17,093] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:35:17,213] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:35:17,307] {logging_mixin.py:115} INFO - [2024-04-05 19:35:17,307] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:35:17,318] {logging_mixin.py:115} INFO - [2024-04-05 19:35:17,318] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-09-18T00:00:00+00:00, run_after=2023-09-25T00:00:00+00:00
[2024-04-05 19:35:17,338] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.248 seconds
[2024-04-05 19:36:27,015] {processor.py:153} INFO - Started process (PID=725964) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:36:27,016] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:36:27,016] {logging_mixin.py:115} INFO - [2024-04-05 19:36:27,016] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:36:27,118] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:36:27,127] {logging_mixin.py:115} INFO - [2024-04-05 19:36:27,127] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:36:27,205] {logging_mixin.py:115} INFO - [2024-04-05 19:36:27,205] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-01-22T00:00:00+00:00, run_after=2024-01-29T00:00:00+00:00
[2024-04-05 19:36:27,218] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.205 seconds
[2024-04-05 19:37:11,326] {processor.py:153} INFO - Started process (PID=726385) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:37:11,329] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:37:11,331] {logging_mixin.py:115} INFO - [2024-04-05 19:37:11,331] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:37:11,455] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:37:11,464] {logging_mixin.py:115} INFO - [2024-04-05 19:37:11,464] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:37:11,548] {logging_mixin.py:115} INFO - [2024-04-05 19:37:11,548] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:37:11,565] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.245 seconds
[2024-04-05 19:37:45,695] {processor.py:153} INFO - Started process (PID=726523) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:37:45,698] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:37:45,698] {logging_mixin.py:115} INFO - [2024-04-05 19:37:45,698] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:37:45,795] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:37:45,803] {logging_mixin.py:115} INFO - [2024-04-05 19:37:45,803] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:37:45,876] {logging_mixin.py:115} INFO - [2024-04-05 19:37:45,876] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:37:45,893] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.201 seconds
[2024-04-05 19:38:16,592] {processor.py:153} INFO - Started process (PID=726668) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:38:16,596] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:38:16,596] {logging_mixin.py:115} INFO - [2024-04-05 19:38:16,596] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:38:16,696] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:38:16,704] {logging_mixin.py:115} INFO - [2024-04-05 19:38:16,704] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:38:16,792] {logging_mixin.py:115} INFO - [2024-04-05 19:38:16,792] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:38:16,809] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.221 seconds
[2024-04-05 19:38:47,486] {processor.py:153} INFO - Started process (PID=726804) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:38:47,489] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:38:47,489] {logging_mixin.py:115} INFO - [2024-04-05 19:38:47,489] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:38:47,587] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:38:47,596] {logging_mixin.py:115} INFO - [2024-04-05 19:38:47,596] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:38:47,671] {logging_mixin.py:115} INFO - [2024-04-05 19:38:47,670] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:38:47,686] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.203 seconds
[2024-04-05 19:39:19,441] {processor.py:153} INFO - Started process (PID=726930) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:39:19,444] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:39:19,444] {logging_mixin.py:115} INFO - [2024-04-05 19:39:19,444] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:39:19,560] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:39:19,570] {logging_mixin.py:115} INFO - [2024-04-05 19:39:19,570] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:39:19,650] {logging_mixin.py:115} INFO - [2024-04-05 19:39:19,650] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:39:19,665] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.226 seconds
[2024-04-05 19:39:54,992] {processor.py:153} INFO - Started process (PID=727098) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:39:54,995] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:39:54,996] {logging_mixin.py:115} INFO - [2024-04-05 19:39:54,996] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:39:55,107] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:39:55,117] {logging_mixin.py:115} INFO - [2024-04-05 19:39:55,117] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:39:55,204] {logging_mixin.py:115} INFO - [2024-04-05 19:39:55,203] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:39:55,220] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.230 seconds
[2024-04-05 19:40:28,682] {processor.py:153} INFO - Started process (PID=727229) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:40:28,685] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:40:28,685] {logging_mixin.py:115} INFO - [2024-04-05 19:40:28,685] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:40:28,811] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:40:28,822] {logging_mixin.py:115} INFO - [2024-04-05 19:40:28,821] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:40:28,905] {logging_mixin.py:115} INFO - [2024-04-05 19:40:28,905] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:40:28,922] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.242 seconds
[2024-04-05 19:41:00,804] {processor.py:153} INFO - Started process (PID=727350) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:41:00,807] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:41:00,807] {logging_mixin.py:115} INFO - [2024-04-05 19:41:00,807] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:41:00,918] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:41:00,936] {logging_mixin.py:115} INFO - [2024-04-05 19:41:00,936] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:41:01,014] {logging_mixin.py:115} INFO - [2024-04-05 19:41:01,014] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:41:01,032] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.231 seconds
[2024-04-05 19:41:31,436] {processor.py:153} INFO - Started process (PID=727470) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:41:31,439] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:41:31,439] {logging_mixin.py:115} INFO - [2024-04-05 19:41:31,439] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:41:31,549] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:41:31,558] {logging_mixin.py:115} INFO - [2024-04-05 19:41:31,558] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:41:31,634] {logging_mixin.py:115} INFO - [2024-04-05 19:41:31,634] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:41:31,649] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.217 seconds
[2024-04-05 19:42:06,574] {processor.py:153} INFO - Started process (PID=727607) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:42:06,577] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:42:06,578] {logging_mixin.py:115} INFO - [2024-04-05 19:42:06,578] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:42:06,688] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:42:06,696] {logging_mixin.py:115} INFO - [2024-04-05 19:42:06,696] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:42:06,774] {logging_mixin.py:115} INFO - [2024-04-05 19:42:06,774] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:42:06,790] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.217 seconds
[2024-04-05 19:42:41,574] {processor.py:153} INFO - Started process (PID=727745) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:42:41,577] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:42:41,578] {logging_mixin.py:115} INFO - [2024-04-05 19:42:41,578] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:42:41,686] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:42:41,696] {logging_mixin.py:115} INFO - [2024-04-05 19:42:41,696] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:42:41,779] {logging_mixin.py:115} INFO - [2024-04-05 19:42:41,779] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:42:41,794] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.223 seconds
[2024-04-05 19:43:12,957] {processor.py:153} INFO - Started process (PID=727869) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:43:12,959] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:43:12,959] {logging_mixin.py:115} INFO - [2024-04-05 19:43:12,959] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:43:13,058] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:43:13,065] {logging_mixin.py:115} INFO - [2024-04-05 19:43:13,065] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:43:13,138] {logging_mixin.py:115} INFO - [2024-04-05 19:43:13,137] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:43:13,150] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.196 seconds
[2024-04-05 19:43:43,335] {processor.py:153} INFO - Started process (PID=727986) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:43:43,338] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:43:43,338] {logging_mixin.py:115} INFO - [2024-04-05 19:43:43,338] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:43:43,435] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:43:43,445] {logging_mixin.py:115} INFO - [2024-04-05 19:43:43,445] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:43:43,525] {logging_mixin.py:115} INFO - [2024-04-05 19:43:43,525] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:43:43,540] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.207 seconds
[2024-04-05 19:44:13,765] {processor.py:153} INFO - Started process (PID=728108) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:44:13,766] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:44:13,767] {logging_mixin.py:115} INFO - [2024-04-05 19:44:13,767] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:44:13,892] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:44:13,911] {logging_mixin.py:115} INFO - [2024-04-05 19:44:13,910] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:44:14,083] {logging_mixin.py:115} INFO - [2024-04-05 19:44:14,083] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:44:14,113] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.350 seconds
[2024-04-05 19:44:46,403] {processor.py:153} INFO - Started process (PID=728239) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:44:46,404] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:44:46,404] {logging_mixin.py:115} INFO - [2024-04-05 19:44:46,404] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:44:46,506] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:44:46,516] {logging_mixin.py:115} INFO - [2024-04-05 19:44:46,516] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:44:46,598] {logging_mixin.py:115} INFO - [2024-04-05 19:44:46,598] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:44:46,613] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.212 seconds
[2024-04-05 19:45:20,682] {processor.py:153} INFO - Started process (PID=728370) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:45:20,685] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:45:20,685] {logging_mixin.py:115} INFO - [2024-04-05 19:45:20,685] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:45:20,793] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:45:20,803] {logging_mixin.py:115} INFO - [2024-04-05 19:45:20,803] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:45:20,875] {logging_mixin.py:115} INFO - [2024-04-05 19:45:20,875] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:45:20,887] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.208 seconds
[2024-04-05 19:45:52,146] {processor.py:153} INFO - Started process (PID=728494) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:45:52,147] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:45:52,147] {logging_mixin.py:115} INFO - [2024-04-05 19:45:52,147] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:45:52,241] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:45:52,250] {logging_mixin.py:115} INFO - [2024-04-05 19:45:52,250] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:45:52,318] {logging_mixin.py:115} INFO - [2024-04-05 19:45:52,318] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:45:52,333] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.189 seconds
[2024-04-05 19:46:25,748] {processor.py:153} INFO - Started process (PID=728631) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:46:25,751] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:46:25,751] {logging_mixin.py:115} INFO - [2024-04-05 19:46:25,751] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:46:25,870] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:46:25,880] {logging_mixin.py:115} INFO - [2024-04-05 19:46:25,880] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:46:25,957] {logging_mixin.py:115} INFO - [2024-04-05 19:46:25,956] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:46:25,974] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.228 seconds
[2024-04-05 19:46:58,597] {processor.py:153} INFO - Started process (PID=728766) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:46:58,599] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:46:58,600] {logging_mixin.py:115} INFO - [2024-04-05 19:46:58,599] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:46:58,704] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:46:58,712] {logging_mixin.py:115} INFO - [2024-04-05 19:46:58,712] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:46:58,783] {logging_mixin.py:115} INFO - [2024-04-05 19:46:58,783] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:46:58,797] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.202 seconds
[2024-04-05 19:47:31,895] {processor.py:153} INFO - Started process (PID=728908) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:47:31,896] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:47:31,897] {logging_mixin.py:115} INFO - [2024-04-05 19:47:31,897] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:47:32,000] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:47:32,010] {logging_mixin.py:115} INFO - [2024-04-05 19:47:32,010] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:47:32,078] {logging_mixin.py:115} INFO - [2024-04-05 19:47:32,077] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:47:32,091] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.198 seconds
[2024-04-05 19:48:03,284] {processor.py:153} INFO - Started process (PID=729045) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:48:03,287] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:48:03,288] {logging_mixin.py:115} INFO - [2024-04-05 19:48:03,287] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:48:03,387] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:48:03,395] {logging_mixin.py:115} INFO - [2024-04-05 19:48:03,395] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:48:03,466] {logging_mixin.py:115} INFO - [2024-04-05 19:48:03,466] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:48:03,480] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.200 seconds
[2024-04-05 19:48:36,193] {processor.py:153} INFO - Started process (PID=729179) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:48:36,195] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:48:36,196] {logging_mixin.py:115} INFO - [2024-04-05 19:48:36,196] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:48:36,290] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:48:36,298] {logging_mixin.py:115} INFO - [2024-04-05 19:48:36,298] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:48:36,368] {logging_mixin.py:115} INFO - [2024-04-05 19:48:36,367] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:48:36,381] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.190 seconds
[2024-04-05 19:49:09,235] {processor.py:153} INFO - Started process (PID=729325) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:49:09,236] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:49:09,236] {logging_mixin.py:115} INFO - [2024-04-05 19:49:09,236] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:49:09,421] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:49:09,440] {logging_mixin.py:115} INFO - [2024-04-05 19:49:09,440] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:49:09,536] {logging_mixin.py:115} INFO - [2024-04-05 19:49:09,536] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:49:09,550] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.317 seconds
[2024-04-05 19:49:43,704] {processor.py:153} INFO - Started process (PID=729460) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:49:43,705] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:49:43,705] {logging_mixin.py:115} INFO - [2024-04-05 19:49:43,705] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:49:43,805] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:49:43,814] {logging_mixin.py:115} INFO - [2024-04-05 19:49:43,814] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:49:43,885] {logging_mixin.py:115} INFO - [2024-04-05 19:49:43,884] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:49:43,898] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.196 seconds
[2024-04-05 19:50:17,433] {processor.py:153} INFO - Started process (PID=729591) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:50:17,435] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:50:17,436] {logging_mixin.py:115} INFO - [2024-04-05 19:50:17,436] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:50:17,533] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:50:17,606] {logging_mixin.py:115} INFO - [2024-04-05 19:50:17,606] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:50:17,616] {logging_mixin.py:115} INFO - [2024-04-05 19:50:17,616] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:50:17,633] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.202 seconds
[2024-04-05 19:50:50,284] {processor.py:153} INFO - Started process (PID=729720) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:50:50,288] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:50:50,288] {logging_mixin.py:115} INFO - [2024-04-05 19:50:50,288] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:50:50,387] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:50:50,451] {logging_mixin.py:115} INFO - [2024-04-05 19:50:50,451] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:50:50,458] {logging_mixin.py:115} INFO - [2024-04-05 19:50:50,458] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:50:50,471] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.190 seconds
[2024-04-05 19:51:22,501] {processor.py:153} INFO - Started process (PID=729851) to work on /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:51:22,504] {processor.py:641} INFO - Processing file /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py for tasks to queue
[2024-04-05 19:51:22,504] {logging_mixin.py:115} INFO - [2024-04-05 19:51:22,504] {dagbag.py:507} INFO - Filling up the DagBag from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:51:22,599] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py
[2024-04-05 19:51:22,695] {logging_mixin.py:115} INFO - [2024-04-05 19:51:22,695] {dag.py:2379} INFO - Sync 1 DAGs
[2024-04-05 19:51:22,707] {logging_mixin.py:115} INFO - [2024-04-05 19:51:22,706] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2024-04-01T00:00:00+00:00, run_after=2024-04-08T00:00:00+00:00
[2024-04-05 19:51:22,722] {processor.py:161} INFO - Processing /home/dimitri/dimitri/airflowalura/dags/extrai_dados_climaticos.py took 0.224 seconds
